### ISSUE TITLE
AttributeError: COPA.

### ISSUE THREAD

**Issue by noobimp** [Shivanshu-Gupta/in-context-learning#2]
Hi Gupta,
When i run `python src/experiments.py`, I got the error bellow:
```
Traceback (most recent call last):
  File "/data/in-context-learning/src/experiments.py", line 15, in <module>
    from params import AllParams, ExperimentParams, LLMParams, sel2cls
  File "/data/in-context-learning/src/params.py", line 20, in <module>
    from data_params import DataParams, ds2cls
  File "/data/in-context-learning/src/data_params.py", line 719, in <module>
    class COPA(DataParams):
  File "/data/in-context-learning/src/data_params.py", line 720, in COPA
    dataset: D = D.COPA
  File "envs/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: COPA.
```
Can you tell me what's causing this error? Thank you!

**Comment by Shivanshu-Gupta** [comment]
Sorry about the late response. The relevant constants were missing in constants.py. It's been fixed now.
